In [55]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [56]:
X = tf.constant(range(12))
print(X.shape)

(12,)


In [57]:
X

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [58]:
X.shape

TensorShape([12])

In [59]:
len(X)

12

In [60]:
X = tf.reshape(X,(3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [61]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [62]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [63]:
Y = tf.constant([[1,2,3,4],[1,3,4,5],[2,5,6,7]])

In [64]:
tf.random.normal(shape=[3,4],mean=0,stddev=1)



<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.13260396,  1.1224352 , -1.6358784 ,  0.49802408],
       [-1.2034265 , -0.5580513 , -1.1324824 , -0.84517187],
       [-0.7638639 ,  0.09752779,  1.0561385 ,  2.1545196 ]],
      dtype=float32)>

In [65]:
X+Y


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [ 5,  8, 10, 12],
       [10, 14, 16, 18]])>

In [66]:
X*Y


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  2,  6, 12],
       [ 4, 15, 24, 35],
       [16, 45, 60, 77]])>

In [67]:
X/Y

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[0.        , 0.5       , 0.66666667, 0.75      ],
       [4.        , 1.66666667, 1.5       , 1.4       ],
       [4.        , 1.8       , 1.66666667, 1.57142857]])>

In [68]:
Y =tf.cast(Y,tf.float64)
tf.exp(Y)

<tf.Tensor: shape=(3, 4), dtype=float64, numpy=
array([[   2.71828183,    7.3890561 ,   20.08553692,   54.59815003],
       [   2.71828183,   20.08553692,   54.59815003,  148.4131591 ],
       [   7.3890561 ,  148.4131591 ,  403.42879349, 1096.63315843]])>

In [69]:
Y = tf.cast(Y,tf.int32)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 20,  26,  38],
       [ 60,  78, 118],
       [100, 130, 198]])>

In [70]:
tf.concat([X,Y],axis=0),tf.concat([X,Y],axis=1)

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2,  3,  4],
        [ 1,  3,  4,  5],
        [ 2,  5,  6,  7]])>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  1,  2,  3,  4],
        [ 4,  5,  6,  7,  1,  3,  4,  5],
        [ 8,  9, 10, 11,  2,  5,  6,  7]])>)

In [71]:
tf.equal(X,Y)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [72]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [73]:
# 求范数
X = tf.cast(X,tf.float32)
tf.norm(X)


<tf.Tensor: shape=(), dtype=float32, numpy=22.494444>

In [74]:
A = tf.reshape(tf.constant(range(3)),(3,1))
B = tf.reshape(tf.constant(range(2)),(1,2))
A,B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [75]:
A+B



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [76]:
X[1:]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [77]:
print(X)
X[:,1:]

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.]], dtype=float32)>

In [78]:
X=tf.Variable(X)
X

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [79]:
X[1:2,1:2].assign(tf.ones(X[1:2,1:2].shape,dtype=tf.float32)*0.5)
X



<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0. ,  1. ,  2. ,  3. ],
       [ 4. ,  0.5,  6. ,  7. ],
       [ 8. ,  9. , 10. , 11. ]], dtype=float32)>

In [80]:
X = tf.Variable(X)
Y = tf.cast(Y,dtype=tf.float32)

before = id(Y)
Y = Y + X
id(Y)==before

False

In [81]:
Z = tf.Variable(tf.zeros_like(Y))
before = id(Z)
Z[:].assign(X+Y)
id(Z) == before



True

In [82]:
Z = tf.add(X,Y)
id(Z) ==before

False

In [83]:
before = id(X)
X.assign_add(Y)
id(X) == before

True

In [85]:
import numpy as np
P = np.ones((2,3))
D = tf.constant(P)
D

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [86]:
np.array(D)

array([[1., 1., 1.],
       [1., 1., 1.]])