In [1]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [2]:
num_input = 2
num_example = 1000
true_w = [2,-3.4]
true_b = 4.2
features = tf.random.normal(shape=(num_example,num_input),stddev=1)
labels = true_w[0] * features[:,0]+true_w[1]*features[:,1]+true_b
labels += tf.random.normal(labels.shape,stddev=0.01)

In [3]:
from tensorflow import data as tddata

batch_size = 10
# 将训练数据的特征和标签组合
dataset = tddata.Dataset.from_tensor_slices((features,labels))
# 随机读取小批量
dataset = dataset.shuffle(buffer_size=num_example)
dataset = dataset.batch(batch_size)
data_iter = iter(dataset)

In [5]:
for (batch,(X, y)) in enumerate(dataset):
    print(batch,X,y)
    break

0 tf.Tensor(
[[-1.3183944   0.88571453]
 [ 0.5582473   0.6283028 ]
 [ 0.3318851   0.30217335]
 [ 0.5585688   1.625666  ]
 [ 1.3739443  -0.2193088 ]
 [-1.1692793  -1.3866609 ]
 [ 0.76365966  1.0310326 ]
 [-1.7447253   1.4246174 ]
 [-0.4479057  -0.52858967]
 [ 0.6691452  -0.44063178]], shape=(10, 2), dtype=float32) tf.Tensor(
[-1.4440066   3.1915112   3.8415916  -0.20795591  7.6803966   6.574926
  2.2208211  -4.1473265   5.0976176   7.0480514 ], shape=(10,), dtype=float32)


In [6]:

from tensorflow import keras
from tensorflow import initializers as init

model = keras.Sequential()
model.add(keras.layers.Dense(1,kernel_initializer=init.RandomNormal(stddev=0.01)))

In [7]:
from tensorflow import losses

loss = losses.MeanSquaredError()

In [8]:
from tensorflow import optimizers

trainer = optimizers.SGD(learning_rate=0.03)

In [9]:
num_epochs =  3
for epoch in range(1,num_epochs+1):
    for (batch,(X,y)) in enumerate(dataset):
        with tf.GradientTape() as t:
            l = loss(model(X,training=True),y)
        grads = t.gradient(l, model.trainable_variables)
        trainer.apply_gradients(zip(grads,model.trainable_variables))
    l = loss(model(features),labels)
    print('epoch %d, loss: %f' % (epoch, l))

epoch 1, loss: 0.000222
epoch 2, loss: 0.000099
epoch 3, loss: 0.000100


In [10]:
true_w,model.get_weights()[0]

([2, -3.4],
 array([[ 2.0009027],
        [-3.4000764]], dtype=float32))

In [11]:
true_b,model.get_weights()[1]

(4.2, array([4.2001143], dtype=float32))